### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by AOPALUNPA** [MengyuanChen21/UDEL#2]
Hello, thanks for your excellent work. I wonder when can you release the official code?

**Comment by AOPALUNPA** [comment]
Any updates?

**Comment by AOPALUNPA** [comment]
If you don't release your code, please don't mention it within your paper. This can be viewed as deception and fraud

**Comment by MengyuanChen21** [comment]
Hello, thank you for your interest in our work. I am maintaining several GitHub projects on my own, and the heavy demands of scientific work do not allow me enough time. The current version of the code includes pre-trained models and testing code that can replicate the performance presented in the paper. I will complete the code organization and checks, and publish the full code when I have enough time. Additionally, the conference version of this paper published at ECCV 2022 has a better code repository at `https://github.com/MengyuanChen21/ECCV2022-DELU`, which may be helpful for your work.

**Comment by AOPALUNPA** [comment]
> Hello, thank you for your interest in our work. I am maintaining several GitHub projects on my own, and the heavy demands of scientific work do not allow me enough time. The current version of the code includes pre-trained models and testing code that can replicate the performance presented in the paper. I will complete the code organization and checks, and publish the full code when I have enough time. Additionally, the conference version of this paper published at ECCV 2022 has a better code repository at `https://github.com/MengyuanChen21/ECCV2022-DELU`, which may be helpful for your work.

Thanks a lot for your reply! I appreciate the release of the code.  Excellent work!
